{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2galaxy
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python  {{ python }}
    - setuptools

  run:
    - python  {{ python }}
    - qiime2 {{ release }}.*
    - q2-mystery-stew {{ release }}.*
    - lxml

test:
  imports:
    - q2galaxy
  commands:
    - q2galaxy template tests $(mktemp -d)


about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
